export const HOST_FEE=50
export const DISPUTE_FEE=50
export const WITHDRAWL_AMOUNT=0.97
export const MIN_PREDICTION_AMOUNT=10
export const DEPOSIT_WALLET="5G3nNt5W44KUnygyRVLHxxbkZCYyYSsUJAbZZuQ2SzNia5jF"