import type { Metadata } from "next"
import Providers from "./providers"
import "react-datepicker/dist/react-datepicker.css"
import "react-responsive-modal/styles.css"
import "react-toastify/dist/ReactToastify.css"
import "./globals.css"

export const metadata: Metadata = {
  title: "PredictionDex",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@300,301,400,401,500,501,700,701,900,901&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
